apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../app/deployment.yaml
  - ../../app/hpa.yaml
  - ../../app/service.yaml
patchesStrategicMerge:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: podinfo
  replicas:
    count: 1
  