apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../app/deployment.yaml
  - ../../app/service.yaml
  - ./service-extern.yaml
patchesStrategicMerge:
-  ./replica_count.yaml
  