---
apiVersion: v1
kind: Service
metadata:
  name: podinfo_extern
  labels:
    app: podinfo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: NodePort
